version: "3.9"
   
services:
  nginx:
      build:
        context : ./nginx/
        dockerfile: Nginx.Dockerfile
      depends_on:
        - web
      ports:
        - "5100:5100"
      restart: always

  web:
    image: python:3.9
    build: .
    command: python -m gunicorn AppServer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./AppServer/.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - .:/var
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  
